#配置连接池相关的信息,因为springboot并不知道我们的链接地址是哪里
spring:
  datasource:
    url: jdbc:mysql:///dudu
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 10.9.251.200
    port: 8100
    password: redis001
    pool:
      max-active: 1024
      max-idle: 512
      min-idle: 200
      max-wait: 10000
mybatis:

  config-location: classpath:mybatis/myabtis.xml
pagehelper:
  helper-dialect: mysql
  params: count=countsql
server:
  port: 8080