server:
  port: 8100
spring:
  datasource:
    url: jdbc:///p2p?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
pagehelper:
  helper-dialect: mysql
  params: count=countsql


